

pretrained_root: 'checkpoints'

################################################################################
# training parameters
################################################################################
train:
  max_epochs: 50
  wup_epochs: 1          # warmup during first XX epochs (can be float)
  batch_size: 1         # batch size
  report_epoch: 3        # every x epochs, report validation set
  save_summary: False    # Summary of weight histograms for tensorboard
  save_scans: True       # False doesn't save anything, True saves some 
                         # sample images (one per batch of the last calculated batch)
                         # in log folder
  workers:  0            # number of threads to get data
  fraction: 0.01   # percentage of samples in the training and validation sets used 
                        # for training in the development stage
  rotation_size: -1
  shuffle: True
  split: # sequence number
    - '02'

  rotation:
    - 180
    - 150
  
loss_function:
  margin: 0
  reduction: 'mean'

################################################################################
# Validation parameters
################################################################################

test:
  gt: False
  shuffle: False
  batch_size: 1
  fraction: 0.01
  split: # sequence numbers
    - '00'
  


