loss_function:
  margin: 0.85
  reduction: sum
name: cross_val_02
pretrained_root: checkpoints
test:
  batch_size: 1
  fraction: 0.2
  gt: false
  range_thres: 6
  shuffle: false
  split:
  - '02'
  top_cand: 1
  workers: 0
train:
  batch_size: 1
  fraction: 0.2
  max_epochs: 20
  report_batch: 1
  report_val: 2
  rotation:
    fraction: 0
  rotation_size: 0
  save_scans: true
  save_summary: false
  shuffle: true
  split:
  - '00'
  - '05'
  - '06'
  - 08
  workers: 0
  wup_epochs: 1
