
architecture: [backbone,'attention']

optimizer:
  lr:         0.001               # sgd learning rate
  wup_epochs: 1          # warmup during first XX epochs (can be float)
  momentum:   0.9          # sgd momentum
  lr_decay:   0.99         # learning rate decay per epoch after initial cycle (from min lr)
  w_decay:    0.00001       # weight decay
  betas:      [0.9, 0.99]
  epsilon_w:  0.00001
  amsgrad:    True


device: 'cuda:1'

################################################################################
# backbone parameters
################################################################################
backbone:
  name: "darknetv3"  # ['squeezeseg', 'squeezesegV2', 'darknet']
  input_depth:
    range: True
    xyz: True
    remission: True
  dropout: 0.05
  bn_d: 0.01
  OS: 32 # output stride (only horizontally)
  train: True # train backbone?
  extra:
    layers: 53
  encoders: [0,1,2,3]

################################################################################
# decoder parameters
################################################################################
fc:
  name:       "fc"
  dropout:    0.05
  input_dim:  1024
  hidden_dim: 1024
  output_dim: 1024
  train: True # train decoder?
  extra: False # nothing to add for this decoder, otherwise this is a dict

################################################################################
# classification head parameters
################################################################################
attention:
  name: "attention"
  use: False
  n_layers: 1
  emb_dim: 512
  train: True
  norm: False

outlayer:
  train: True
  norm:
    dim: [64, 32]

dataset:
  name: 'kitti'
  path: 
    root: "D:\\OneDrive - isr.uc.pt\\Datasets\\Kitti\\odometry_semantic_dataset"
    scan: "velodyne"
  labels: "kitti"
  scans: "kitti"
  max_points: 150000 # max of any scan in dataset
  sensor:
    name: "HDL64"
    type: "spherical" # projective
    fov_up: 3
    fov_down: -25 
    img_prop:
      width: 512
      height: 64
    img_means: #range,x,y,z,signal
      - 12.12
      - 10.88
      - 0.23
      - -1.04
      - 0.21
    img_stds: #range,x,y,z,signal
      - 12.32
      - 11.47
      - 6.91
      - 0.86
      - 0.16


