architecture:
- backbone
- attention
attention:
  emb_dim: 256
  n_layers: 2
  name: attention
  norm: false
  train: true
  use: false
backbone:
  OS: 32
  bn_d: 0.01
  dropout: 0.05
  encoders:
  - 0
  - 1
  - 2
  extra:
    layers: 53
  input_depth:
    range: true
    remission: true
    xyz: true
  name: darknetv3
  train: true
dataset:
  labels: kitti
  max_points: 150000
  name: kitti
  path:
    root: D:\OneDrive - isr.uc.pt\Datasets\Kitti\odometry_semantic_dataset
    scan: velodyne
  scans: kitti
  sensor:
    fov_down: -25
    fov_up: 3
    img_means:
    - 12.12
    - 10.88
    - 0.23
    - -1.04
    - 0.21
    img_prop:
      height: 64
      width: 512
    img_stds:
    - 12.32
    - 11.47
    - 6.91
    - 0.86
    - 0.16
    name: HDL64
    type: spherical
device: cuda:1
fc:
  dropout: 0.05
  extra: false
  hidden_dim: 1024
  input_dim: 1024
  name: fc
  output_dim: 1024
  train: true
optimizer:
  amsgrad: true
  betas:
  - 0.9
  - 0.99
  epsilon_w: 1.0e-05
  lr: 0.001
  lr_decay: 0.99
  momentum: 0.9
  w_decay: 1.0e-05
  wup_epochs: 1
outlayer:
  norm:
    dim:
    - 64
    - 64
  train: true
