architecture:
- backbone
- attention
device: cuda:1
optimizer:
  amsgrad: true
  betas:
  - 0.9
  - 0.99
  epsilon_w: 1.0e-05
  lr: 0.001
  lr_decay: 0.99
  momentum: 0.9
  w_decay: 1.0e-05
  wup_epochs: 1
